---
version: '3'
services:

  moneybox-db:
    image: postgres:alpine3.18
    container_name: moneybox-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=moneybox
      - POSTGRES_USER=moneybox
      - POSTGRES_PASSWORD=password
      
  moneybox-gateway:
    build: ./moneybox-gateway
    image: moneybox-gateway-image
    container_name: moneybox-gateway-container
    ports:
      - "8080:8080"

  moneybox-sever:
    build: ./moneybox-server
    image: moneybox-sever-image
    container_name: moneybox-sever-container
    ports:
      - "8085:8085"
    depends_on:
      - moneybox-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://moneybox-db:5432/moneybox
      - POSTGRES_USER=moneybox
      - POSTGRES_PASSWORD=password

  moneybox-console-logger:
    build: ./transfer-console-logger
    image: moneybox-console-logger-image
    container_name: moneybox-console-logger-container
    ports:
      - "8082:8082"

  moneybox-auto-transfer:
    build: ./auto-transfer-client
    image: moneybox-auto-transfer-image
    container_name: moneybox-auto-transfer-container
    ports:
      - "8081:8081"
